In [30]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

K = len(np.unique(y_train)) # Return the unique elements of a tratining output set and take it length as Classes
Ntr = x_train.shape[0] # number of training examples
Nte = x_test.shape[0] # number of testing examples
Din = 3072 # By CIFAR10 data set with 32 x 32 x 3 color images

# Normalize pixel values: Image data preprocessing
x_train, x_test = x_train / 255.0, x_test / 255.0
mean_image = np.mean(x_train, axis=0) # axis=0: mean of a column; Mean of each pixel
x_train = x_train - mean_image
x_test = x_test - mean_image


y_train = tf.keras.utils.to_categorical(y_train, num_classes=K) # This function returns a matrix of binary values (either ‘1’ or ‘0’). It has number of rows equal to the length of the input vector and number of columns equal to the number of classes.
y_test = tf.keras.utils.to_categorical(y_test, num_classes=K)
x_train = np.reshape(x_train,(Ntr,Din)).astype('float32') # reshape the data set
x_test = np.reshape(x_test,(Nte,Din)).astype('float32')

std=1e-5 # standard deviation (sigma)
w = std*np.random.randn(Din, K) #Return a sample (or samples) from the “standard normal” distribution.
b = np.zeros(K) # creating array of zeros for bias vector

print("w:", w.shape)
print("b:", b.shape)
#batch_size = Ntr # for gradient descent optimization batch size is equal to number of training set

iterations = 300 # epochs
lr = 1.4e-2 # the learning rate alpha
lr_decay = 0.999
reg = 5e-6 # the regularization constant
loss_history = []
train_acc_history = []
val_acc_history = []

for t in range(iterations):
    # forward propagation
    batch_indices = np.random.choice(Ntr, Ntr) # Generates a random sample from a given 1-D array
    x = x_train[batch_indices]
    y = y_train[batch_indices]
    y_pred = x.dot(w) + b # create predictable output
    loss = (1/Ntr)*np.square(y_pred - y).sum() +  reg*(np.sum(w**2) # loss function with regularization term 
    loss_history.append(loss)

    # backward propagation

    if t % 10 == 0:
        print('iteration %d / %d: loss %f' % (t, iterations, loss))





x_train: (10000, 32, 32, 3)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
(10000, 10)
[[-0.2812186  -0.29041624 -0.27276    ... -0.0142709  -0.13274628
  -0.16620338]
 [ 0.09133043  0.16056415  0.2135145  ...  0.06416047  0.02803804
   0.11614957]
 [ 0.48740888  0.46644652  0.4801812  ... -0.18289836 -0.15627569
  -0.11914455]
 ...
 [-0.37533623  0.16448572  0.4017498  ... -0.44956502 -0.37196195
  -0.25247788]
 [ 0.22858533  0.29389748  0.42135766 ...  0.26808205  0.25156745
   0.22203192]
 [ 0.38544807  0.3644857   0.4174361  ...  0.14259185  0.14568509
   0.18281624]]
(50000, 3072)
